"""rename is_archived to is_completed

Revision ID: f64b7a6bc336
Revises: 9ab8e92ebbe3
Create Date: 2025-03-10 14:33:52.630651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64b7a6bc336'
down_revision: Union[str, None] = '9ab8e92ebbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('is_completed', sa.Integer(), nullable=False))
    op.drop_column('habits', 'is_archived')
    op.add_column('tasks', sa.Column('is_completed', sa.Integer(), nullable=False))
    op.drop_column('tasks', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_archived', sa.INTEGER(), nullable=False))
    op.drop_column('tasks', 'is_completed')
    op.add_column('habits', sa.Column('is_archived', sa.INTEGER(), nullable=False))
    op.drop_column('habits', 'is_completed')
    # ### end Alembic commands ###
